
var ajgroups = require('../'),
    assert = require('assert');
    
// Symmetric 2 is cyclic

var symmetric2 = ajgroups.symmetric(2);
assert.equal(symmetric2.isCyclic(), true);

// Symmetric 3 is not cyclic

var symmetric3 = ajgroups.symmetric(3);
assert.equal(symmetric3.isCyclic(), false);

// Symmetric 4 is not cyclic

var symmetric4 = ajgroups.symmetric(4);
assert.equal(symmetric4.isCyclic(), false);

// Group generated by cyclic element

var cyclic3 = ajgroups.cyclic(3);
var group = ajgroups.createGroup(cyclic3);
assert.equal(group.isCyclic(), true);

// Exchanges are cyclic

for (var k = 2; k <= 6; k++)
    assert.equal(ajgroups.createGroup(ajgroups.cyclic(k)).isCyclic(), true);
    
// Groups generated by cyclic permutation are cyclic

for (var k = 2; k <= 6; k++)
    assert.equal(ajgroups.createGroup(ajgroups.exchange(k)).isCyclic(), true);
    
