
const ajgroups = require('../');
const assert = require('assert');
    
// Symmetric 2 is cyclic

{
    const symmetric2 = ajgroups.symmetric(2);

    assert.equal(symmetric2.isCyclic(), true);
}

// Symmetric 3 is not cyclic

{
    const symmetric3 = ajgroups.symmetric(3);

    assert.equal(symmetric3.isCyclic(), false);
}

// Symmetric 4 is not cyclic

{
    const symmetric4 = ajgroups.symmetric(4);

    assert.equal(symmetric4.isCyclic(), false);
}

// Group generated by cyclic element

{
    const cyclic3 = ajgroups.cyclic(3);
    const group = ajgroups.createGroup(cyclic3);

    assert.equal(group.isCyclic(), true);
}

// Exchanges are cyclic

{
    for (let k = 2; k <= 6; k++)
        assert.equal(ajgroups.createGroup(ajgroups.cyclic(k)).isCyclic(), true);
}
    
// Groups generated by cyclic permutation are cyclic

{
    for (let k = 2; k <= 6; k++)
        assert.equal(ajgroups.createGroup(ajgroups.exchange(k)).isCyclic(), true);
}
    

    